const express = require('express')
const methodoverride = require('method-override')
const dbcon = require('./db_connect')
const cookieparser = require('cookie-parser')
const PORT = process.env.PORT || 5000
const path = require('path')
const stat = path.join(__dirname, './public')
const views = path.join(__dirname, './views')
const app = express()
app.set('views', views)
app.set('view engine', 'ejs')
app.use(express.static(stat))
app.use(methodoverride('_method'))
app.use(express.json())
app.use(cookieparser())
app.use(express.urlencoded({ extended: false }))
dbcon()
app.use("*", require('./middlewares/userMiddleWare'))
app.use(require('./routes/auth'))
app.use(require('./routes/main'))
app.use(require('./routes/stripe'))
app.listen(PORT, () => console.log(`connected to ${PORT}`))